alias ncal='ncal -bMw'
alias year='ncal -y'
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'
alias copylastcommand='history -p \!\! | xsel -ib'
#alias use_bitwig='pactl set-default-sink alsa_output.usb-Bitwig_GmbH_Bitwig_Connect_BWCAr3Xf2-00.multichannel-output'
