#+TITLE: Migges's dotfiles
#+AUTHOR: Migge
#+DESCRIPTION: Description and dotfiles for some of my Linux configuration
#+STARTUP: showeverything

* Fonts

My setup is dependent on a font used by the terminal, namely
SourceCodePro (or Sauce Code Pro) from the Nerd Fonts collection. The
latest version is always available at the following link:

https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.tar.xz

, and should be unpacked into a fonts directory of your choice. Since
I plan to include this in an upcoming script, the preferred location,
which is one of the default ones the system will look for, is the
~.fonts/~ directory in your home, as then the script won't require
root privileges.

* Alacritty

Currently my terminal of choice. Actually I am one of those who have
nothing against the standard Gnome terminal; main reason for switching
is to easier get rid of the window title bar, which is surprisingly
difficult to do. Plus these hipster terminals such as Kitty and
Alacritty seems to just play along more nicely with tiling window
managers in general and highly customizable while still keeping the
config file rather small.

Which this one currently is. As of today it only contains the Dracula
theme, font selection, and some slight window transparency.
